[build]
publish = "dist"
command = "bun run build"

[[headers]]
for = "/*"
[headers.values]
X-Content-Type-Options = "nosniff"
Content-Security-Policy = """
    default-src 'self';
    frame-ancestors 'self';
    style-src 'self' 'unsafe-inline';
    """

[[headers]]
for = "/_astro/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/fonts/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.ico"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.svg"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.png"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
