[build]
publish = "dist"
command = "bun run build"

[[headers]]
for = "/*"
[headers.values]
X-Content-Type-Options = "nosniff"
Content-Security-Policy = """
    default-src 'self';
    frame-ancestors 'self';
    style-src 'self' 'unsafe-inline';
	script-src 'self' cloud.umami.is;
	connect-src 'self' *.umami.dev;
	frame-src 'self' codepen.io;
    img-src 'self' data:;
    """
Cross-Origin-Resource-Policy = "same-origin"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/_astro/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/fonts/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.ico"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.svg"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.png"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
