name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Cache Bun packages
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.OS }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.OS }}-bun-
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-modules-${{ hashFiles('**/bun.lockb') }}

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-modules-${{ hashFiles('**/bun.lockb') }}
      - name: Run ESLint
        run: bun run eslint

  stylelint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-modules-${{ hashFiles('**/bun.lockb') }}
      - name: Run Stylelint
        run: bun run stylelint
